# Autogenerated from /home/max/GitHub/llvm-project/clang-tools-extra/test/Unit/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
def path(p):
    if not p: return ''
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), p)


config.extra_tools_obj_dir = "/home/max/GitHub/llvm-project/build/tools/clang/tools/extra/test/../unittests"
config.extra_tools_src_dir = "/home/max/GitHub/llvm-project/clang-tools-extra/test/../unittests"
config.llvm_libs_dir = "/home/max/GitHub/llvm-project/build/./lib"
config.shlibdir = "/home/max/GitHub/llvm-project/build/./lib"
config.target_triple = "x86_64-unknown-linux-gnu"

lit_config.load_config(config, "/home/max/GitHub/llvm-project/clang-tools-extra/test/../test/Unit/lit.cfg.py")
