# Autogenerated from /Users/maxwellkapral/llvm-project/clang-tools-extra/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
def path(p):
    if not p: return ''
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), p)


import sys

config.llvm_tools_dir = "/Users/maxwellkapral/llvm-project/build/./bin"
config.llvm_libs_dir = "/Users/maxwellkapral/llvm-project/build/./lib"
config.lit_tools_dir = ""
config.clang_tools_binary_dir = "/Users/maxwellkapral/llvm-project/build/tools/clang/tools/extra/test/.."
config.clang_tools_dir = "/Users/maxwellkapral/llvm-project/build/./bin"
config.clang_libs_dir = "/Users/maxwellkapral/llvm-project/build/./lib"
config.python_executable = "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8"
config.target_triple = "x86_64-apple-darwin19.6.0"
config.clang_tidy_staticanalyzer = 1
config.libclang_include_clang_tools_extra = 0

# Support substitution of the tools and libs dirs with user parameters. This is
# used when we can't determine the tool dir at configuration time.
try:
    config.clang_tools_dir = config.clang_tools_dir % lit_config.params
    config.llvm_tools_dir = config.llvm_tools_dir % lit_config.params
    config.llvm_libs_dir = config.llvm_libs_dir % lit_config.params
except KeyError:
    e = sys.exc_info()[1]
    key, = e.args
    lit_config.fatal("unable to find %r parameter, use '--param=%s=VALUE'" % (key,key))

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(config, "/Users/maxwellkapral/llvm-project/clang-tools-extra/test/../test/lit.cfg.py")
