# Autogenerated from /Users/maxwellkapral/llvm-project/clang-tools-extra/clangd/unittests/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
def path(p):
    if not p: return ''
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), p)

# This is a shim to run the gtest unittests in ../unittests using lit.

config.llvm_libs_dir = "/Users/maxwellkapral/llvm-project/build/./lib"
config.shlibdir = "/Users/maxwellkapral/llvm-project/build/./lib"

config.clangd_source_dir = "/Users/maxwellkapral/llvm-project/clang-tools-extra/clangd/unittests/.."
config.clangd_binary_dir = "/Users/maxwellkapral/llvm-project/build/tools/clang/tools/extra/clangd/unittests/.."

# Delegate logic to lit.cfg.py.
lit_config.load_config(config, "/Users/maxwellkapral/llvm-project/clang-tools-extra/clangd/unittests/lit.cfg.py")
